### ISSUE TITLE
git rev-list -n1 raspi  fatal: ambiguous argument 'raspi': 

### ISSUE THREAD

**Issue by martinsookael** [NodeOS/NodeOS#243]
somehow can't get the installation process going on on Ubuntu 14.04. 

```
PLATFORM=qemu_64 npm install
npm ERR! git rev-list -n1 raspi: fatal: ambiguous argument 'raspi': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 raspi: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 raspi: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 raspi: 
npm ERR! git rev-list -n1 raspi: fatal: ambiguous argument 'raspi': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 raspi: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 raspi: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 raspi: 
npm ERR! git rev-list -n1 raspi: fatal: ambiguous argument 'raspi': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 raspi: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 raspi: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 raspi: 
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 raspi
npm ERR! fatal: ambiguous argument 'raspi': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /nodeos/npm-debug.log
```

**Comment by piranna** [comment]
I have been doing some changes to both use upstream QEmu 2.6.0 (that have
merged the raspi branch changes) and to make the build process more
flexible by not being the repo a patched fork of the original one but
instead download a tarball, but I've not finished them. I'm going to try to
fix them now.

**Comment by piranna** [comment]
@martinsookael, could you be able to test it now? It should be fixed in master.

**Comment by martinsookael** [comment]
Thank you for this and tested! 
Still no luck but a new error though :)
```
PLATFORM=qemu_64 npm install
npm ERR! git rev-list -n1 WIP_aux: fatal: ambiguous argument 'WIP_aux': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 WIP_aux: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 WIP_aux: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 WIP_aux: 
npm ERR! git rev-list -n1 WIP_aux: fatal: ambiguous argument 'WIP_aux': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 WIP_aux: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 WIP_aux: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 WIP_aux: 
npm ERR! git rev-list -n1 WIP_aux: fatal: ambiguous argument 'WIP_aux': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 WIP_aux: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 WIP_aux: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 WIP_aux: 
 
> genext2fs@1.4.1 install /home/root/test1/node_modules/genext2fs
> echo $PATH && prebuild-install -d https://github.com/NodeOS/genext2fs/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build

/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/root/test1/node_modules/genext2fs/node_modules/.bin:/home/root/test1/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
 
> qemu@2.6.0 install /home/root/test1/node_modules/qemu
> prebuild-install -d https://github.com/NodeOS/qemu/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build

-
> genfatfs@1.0.1 install /home/root/test1/node_modules/genfatfs
> prebuild-install -d https://github.com/NodeOS/genfatfs/releases/download/v{version}/{platform}-{arch}.tar.gz || npm run build

npm ERR! Linux 3.16.0-71-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 WIP_aux
npm ERR! fatal: ambiguous argument 'WIP_aux': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/root/test1/npm-debug.log
```

**Comment by piranna** [comment]
Yeah, it's somewhat related, I'm moving from 'prebuild' package to simpler
'prebuild-install' now that they have accepted my patches and didn't fully
found all the placed where I was using it. If you want to send a
pull-request with your patches I will accept them :-)

**Comment by piranna** [comment]
This should be fixed now in master, clossing. Re-open it if it's not working for you.
