### ISSUE TITLE
No such file or directory 'addr2line'

### ISSUE THREAD

**Issue by lite20** [NodeOS/NodeOS#271]
I hit this error attempting to compile NodeOS (build script not modified)

```
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /home/lite/Documents/NodeOS/node_modules/nodeos-usersfs/node_modules/nodeos-nodejs/node_modules/nodeos-cross-toolchain/bin/addr2line
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/lite/Documents/NodeOS/node_modules/nodeos-usersfs/node_modules/nodeos-nodejs/node_modules/nodeos-cross-toolchain/bin/addr2line'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

```

**Comment by piranna** [comment]
This should already be fixed in master, have you downloaded the project and
build it from scratch?
El 2/7/2016 1:32 AM, "Lite McFish" <notifications@github.com> escribió:

I hit this error attempting to compile NodeOS (build script not modified)

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /home/lite/Documents/NodeOS/node_modules/nodeos-usersfs/node_modules/nodeos-nodejs/node_modules/nodeos-cross-toolchain/bin/addr2line
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod
'/home/lite/Documents/NodeOS/node_modules/nodeos-usersfs/node_modules/nodeos-nodejs/node_modules/nodeos-cross-toolchain/bin/addr2line'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NodeOS/NodeOS/issues/271>, or mute the thread
<https://github.com/notifications/unsubscribe/AAgfvnogYRf8EQ1JSMeSfZRUGNnqF9e9ks5qRaOCgaJpZM4JDi-5>
.

**Comment by lite20** [comment]
Yeah but I can try again

**Comment by lite20** [comment]
Nope, this is still an issue on master. I cloned the latest version and tried to compile and hit that error again.

**Comment by piranna** [comment]
Sh*t, there must be a conflict on the dependencies somewhere... :-/

**Comment by lite20** [comment]
@piranna what sort of conflict am I looking for?

**Comment by luii** [comment]
I get this error too with node 6.x.x and 4.x.x try to use 5.12.0.
Or try to issue the command right after you got the error

**Comment by piranna** [comment]
> @piranna what sort of conflict am I looking for?

On your error nodeos-nodejs is using its own copy of
nodeos-cross-toolchains.

**Comment by lite20** [comment]
Ah okay. Which is it to use and how to fix?

**Comment by lite20** [comment]
How would we go about making it use the one we provide? Removing it's local one? Cause it to move up a few parent directories and use that one?

**Comment by lite20** [comment]
@luii 5.12.0 didn't work for me either

**Comment by luii** [comment]
Thats strange, i got these errors when i use the wrong version. DId you try to clone it again and then build it from scratch with 5.12.0?

**Comment by lite20** [comment]
@luii oh I may have forgotten to reset. Let me go ahead and do that.

**Comment by luii** [comment]
@lite20 Do you still have this error?

**Comment by lite20** [comment]
I no longer have my Ubuntu computer, so I'm afraid I can't check at the moment.

**Comment by lite20** [comment]
@luii sorry I forgot to tag you above

**Comment by piranna** [comment]
I think we could close this then?

**Comment by lite20** [comment]
Done :) @piranna

**Comment by piranna** [comment]
Cool then :-)
