### ISSUE TITLE
Unable to install NodeOS

### ISSUE THREAD

**Issue by ayusun** [NodeOS/NodeOS#96]
So I was trying to build Node os. I tried using .build but couldn't find it anywhere. So, I started exploring and opened scripts folder and by seeing the code I executed BigRedButton file(btw nice name :+1: ) and it started downloading bunch of things. Everything was fine but then it threw an error

    Compiling Node.js
    make: *** No rule to make target `clean'.  Stop.
    scripts/install: line 34: /home/ayusun/workspace/nodeos/NodeOS/node_modules/nodeos-   barebones/deps/node/configure: No such file or directory
    Error compiling '/home/ayusun/workspace/nodeos/NodeOS/node_modules/nodeos-barebones/obj/i686/node'

    npm ERR! nodeos-barebones@0.0.0 install: `scripts/install`
    npm ERR! Exit status 11
    npm ERR! 
    npm ERR! Failed at the nodeos-barebones@0.0.0 install script.
    npm ERR! This is most likely a problem with the nodeos-barebones package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     scripts/install
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls nodeos-barebones
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.11.0-26-generic
    npm ERR! command "/home/ayusun/workspace/node.js/bin/node"  "/home/ayusun/workspace/node.js/bin/npm" "install"
    npm ERR! cwd /home/ayusun/workspace/nodeos/NodeOS/scripts
    npm ERR! node -v v0.10.35
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/ayusun/workspace/nodeos/NodeOS/scripts/npm-debug.log
    npm ERR! not ok code 0

I was asked to report this. So i did. Anyways as said in ReadMe, it didn't work in the first try. What should i do now?

Thanks

**Comment by ayusun** [comment]
Btw, I forgot to tell you that i did try docker version

    git clone https://github.com/NodeOS/NodeOS
    cd NodeOS
    sudo docker run -t -i nodeos/nodeos

It didn't do anything just printed these

    docker - version 1.4
    Copyright 2003, Ben Jansens <ben@orodu.net>

    Usage: docker [OPTIONS]

    Options:
      -help             Show this help.
      -display DISPLAY  The X display to connect to.
      -border           The width of the border to put around the
                    system tray icons. Defaults to 1.
      -vertical         Line up the icons vertically. Defaults to
                    horizontally.
      -wmaker           WindowMaker mode. This makes docker a
                    fixed size (64x64) to appear nicely in
                    in WindowMaker.
                    Note: In this mode, you have a fixed
                    number of icons that docker can hold.
      -iconsize SIZE    The size (width and height) to display
                    icons as in the system tray. Defaults to
                    24.
      -color COLOR      The background color to use for the tray.
                    Defaults to whatever color the window
                    manager specifies.

I have never used docker. And i installed it using apt-get install docker. I hope thats not a problem

**Comment by ayusun** [comment]
Ok, After an effort i was able to install Node OS. Turns out that it was some other docker not docker.io. In any case, I was able to execute node os and was able to run few commands on nsh. Although for some reasons RMDIR (EISDIR, illegal operation on a directory) didn't work nor bin-ncurl(ECONNREFUSED) Well in any case the shell was working good. But I couldn't find the code any where.

Because now I would like to do some tinkering the code and see how it works. I would really be glad to contribute something to it. It would be the first time that i have used docker and no idea where it would have kept the code. sorry about that. And I still don't know why that first thing i tried using BigRedButton file didn't work.

**Comment by netlovers** [comment]
I think `bin-ncurl` didn't work because the net is not yet enabled, and I'm not sure about the `RMDIR` issue. Do you have the rights to that directory? What command did you use?

The code is where you first run the `git clone` command. And if you look around and look for the `package.json` and `packages.txt` files you can see the dependencies that you can work on.

**Comment by ayusun** [comment]
My mistake, I again did the steps and tried 

rm fiddler : which actually gave me(EISDIR) and RMDIR actually gives me [execvp(): No such file or directory]

About bin-ncurl : sorry, I didn't follow you, by net did you meant that node js library net.

Regarding code : I didn't git clone, I used docker and downloaded the node os image and directly executed it and it opened nsh. I was hoping it would would download the entire thing and i can directly work on it. 
Well, In any case, it would be very helpful, if you can help me with how to start.

Well, what i did till now was, just git clone this repo.

Then the tutorial with Qemu said to execute ./build, but i couldn't find it. So, I was exploring the files, and found this BigRedButtonfile under scripts folder this downloaded bunch of filesand then it threw an error which I have posted in the post itself.

I am sorry, I am not really accustomed to it. So I may need a little help here

Thanks

**Comment by netlovers** [comment]
Yeah, `rm` is supposed to delete files only so that's the reason for the error message. I'm not sure about `RMDIR`.
By net I meant internet, so no internet access at the moment.

You can try to run these:
```
git clone https://github.com/NodeOS/NodeOS.git
cd NodeOS
PLATFORM=qemu_32 npm install
# And the after downloading and compiling everything
npm start
```
The BigRedButton supposed to build for multiple platforms at once, so you don't have to use it. Your first error message said something about missing node source code, but I think it should work with the commands above.

**Comment by ayusun** [comment]
Ok,  let me try it. I suppose its going to take time. I will comeback later on with the result. Thanks

**Comment by ayusun** [comment]
It again gave an error. Please have a look at it.

    '/home/ayusun/workspace/nodeos/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/out/i686-nodeos-linux-musl/usr' -> '.'
    '/home/ayusun/workspace/nodeos/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos- cross-toolchain/out/i686-nodeos-linux-musl/lib64' -> 'lib'
    Extracting Linux headers
    make: *** No rule to make target `mrproper'.  Stop.

    npm ERR! nodeos-cross-toolchain@0.0.0 install: `scripts/install`
    npm ERR! Exit status 10
    npm ERR! 
    npm ERR! Failed at the nodeos-cross-toolchain@0.0.0 install script.
    npm ERR! This is most likely a problem with the nodeos-cross-toolchain package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     scripts/install
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls nodeos-cross-toolchain
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.13.0-45-generic
    npm ERR! command "/home/ayusun/workspace/node.js/bin/node"  "/home/ayusun/workspace/node.js/bin/npm" "install"
    npm ERR! cwd /home/ayusun/workspace/nodeos/NodeOS
    npm ERR! node -v v0.10.35
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/ayusun/workspace/nodeos/NodeOS/npm-debug.log
    npm ERR! not ok code 0

**Comment by netlovers** [comment]
It builds for me. What operating system do you use? Checking the google results it says something about installing the kernel source for your distribution, however I'm not sure why would that be necessary.

**Comment by ayusun** [comment]
Ubuntu 14.04

Well, I don't really understand it either.
I saw one of the closed issues which also had something like this

https://github.com/NodeOS/NodeOS/issues/91

I probably will try the entire thing once again with the new clone. Apparantly for the OP in the link, it worked that way.

**Comment by ayusun** [comment]
Well, I tried it again, this time there was some progress, but again there was an error

    Successfully compiled Node.js
    Compiling Linux
    #
    # configuration written to .config
    #
    .config:3668:warning: override: reassigning to symbol INITRAMFS_SOURCE
    .config:3675:warning: override: reassigning to symbol MODULES
    .config:3682:warning: override: reassigning to symbol OSF_PARTITION
    .config:3683:warning: override: reassigning to symbol AMIGA_PARTITION
    .config:3685:warning: override: reassigning to symbol BSD_DISKLABEL
    .config:3686:warning: override: reassigning to symbol MINIX_SUBPARTITION
    .config:3687:warning: override: reassigning to symbol SOLARIS_X86_PARTITION
    .config:3688:warning: override: reassigning to symbol UNIXWARE_DISKLABEL
    .config:3690:warning: override: reassigning to symbol SGI_PARTITION
    .config:3692:warning: override: reassigning to symbol SUN_PARTITION
    .config:3699:warning: override: reassigning to symbol NETFILTER_XT_MARK
    .config:3706:warning: override: reassigning to symbol NETFILTER_XT_TARGET_LOG
    .config:3713:warning: override: reassigning to symbol NF_LOG_IPV6
    .config:3720:warning: override: reassigning to symbol HAMRADIO
    .config:3727:warning: override: reassigning to symbol DEVTMPFS_MOUNT
    .config:3734:warning: override: reassigning to symbol X86_PKG_TEMP_THERMAL
    .config:3741:warning: override: reassigning to symbol FUSE_FS
    .config:3743:warning: override: reassigning to symbol OVERLAY_FS
    .config:3750:warning: override: reassigning to symbol MISC_FILESYSTEMS
    .config:3757:warning: override: reassigning to symbol DEBUG_KERNEL
    .config:3764:warning: override: reassigning to symbol STACKTRACE
    .config:3771:warning: override: reassigning to symbol FTRACE
    .config:3778:warning: override: reassigning to symbol VIRTUALIZATION
    .config:3779:warning: override: reassigning to symbol BINARY_PRINTF
    #
    # configuration written to .config
    #
    Setup is 15436 bytes (padded to 15872 bytes).
    System is 9928 kB
    CRC 7bf5d839
    Kernel: arch/x86/boot/bzImage is ready  (#1)
    Successfully compiled Linux
    ‘bzImage’ -> ‘/home/ayusun/workspace/NodeOS/node_modules/nodeos-barebones/out/i686/linux’

    > nodeos-barebones@0.0.0 postinstall /home/ayusun/workspace/NodeOS/node_modules/nodeos-barebones
    > scripts/postinstall

    Successfully built barebones

    > nodeos-initramfs@0.0.0 install /home/ayusun/workspace/NodeOS/node_modules/nodeos-initramfs
    > scripts/install

    /usr/bin/env: node: No such file or directory

    npm ERR! nodeos-initramfs@0.0.0 install: `scripts/install`
    npm ERR! Exit status 210
    npm ERR! 
    npm ERR! Failed at the nodeos-initramfs@0.0.0 install script.
    npm ERR! This is most likely a problem with the nodeos-initramfs package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     scripts/install
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls nodeos-initramfs
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.13.0-45-generic
    npm ERR! command "/home/ayusun/workspace/node.js/bin/node"    "/home/ayusun/workspace/node.js/bin/npm" "install"
    npm ERR! cwd /home/ayusun/workspace/NodeOS
    npm ERR! node -v v0.10.35
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/ayusun/workspace/NodeOS/npm-debug.log
    npm ERR! not ok code 0

If you can tell me how to workaround this error, without actually downloading the entire thing again, as it takes a lot of time
Thanks

**Comment by netlovers** [comment]
Good news is that you don't have do download NodeOS again. But if you don't have node.js v0.11.x (unstable) installed then you have to do that. Or if you have it then you have to link the `node` binary to the `/usr/bin` directory, or find the places in the install scripts that set up the `PATH` and add your node binary's location to it.
After that run the install script again.

**Comment by netlovers** [comment]
This is how you can install node v0.11.x: http://askubuntu.com/a/432890

**Comment by ayusun** [comment]
Thank you for that link. Well that problem is resolved and this is new error something with node-gyp. Is it also dependent on something 

```
../src/sockios.cc: In function 'void GetFlags(const v8::FunctionCallbackInfo<v8::Value>&)':
../src/sockios.cc:48:62: error: 'SIOCSIFNAME' was not declared in this scope
make: *** [Release/obj.target/binding/src/sockios.o] Error 1
make: Leaving directory `/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-ifconfig/node_modules/src-sockios/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ayusun/workspace/NodeOS/node_modules/nodeos-barebones/deps/node/deps/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-45-generic
gyp ERR! command "node" "/home/ayusun/workspace/NodeOS/node_modules/nodeos-barebones/deps/node/deps/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-ifconfig/node_modules/src-sockios
gyp ERR! node -v v0.11.15
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/bin/cat -> /home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-fs/bin/cat
/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/bin/cp -> /home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-fs/bin/cp
/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/bin/ln -> /home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-fs/bin/ln
/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/bin/ls -> /home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-fs/bin/ls
/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/bin/mkdir -> /home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-fs/bin/mkdir
/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/bin/rm -> /home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-fs/bin/rm
/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/bin/mv -> /home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-fs/bin/mv
/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/bin/nsh -> /home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-nsh/nsh.js
/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/bin/man -> /home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/obj/i686/nodeos/lib/node_modules/bin-man/man.js
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "node" "/home/ayusun/workspace/NodeOS/node_modules/nodeos-barebones/deps/node/deps/npm/cli.js" "install" "-g" "--loglevel" "warn" "--arch=ia32" "--nodedir=/home/ayusun/workspace/NodeOS/node_modules/nodeos-usersfs/../nodeos-barebones/deps/node" "--jobs=5" "npm" "bin-ip" "bin-sh" "bin-nsh" "bin-man" "bin-fs" "bin-pwd" "netlovers/node-bin-ifconfig"
npm ERR! node v0.11.15
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE

npm ERR! src-sockios@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the src-sockios@0.1.0 install script.
npm ERR! This is most likely a problem with the src-sockios package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls src-sockios
npm ERR! There is likely additional logging output above.

npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE
npm ERR! nodeos-usersfs@0.0.0 install: `scripts/install`
npm ERR! Exit status 154
npm ERR! 
npm ERR! Failed at the nodeos-usersfs@0.0.0 install script.
npm ERR! This is most likely a problem with the nodeos-usersfs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeos-usersfs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ayusun/workspace/NodeOS/npm-debug.log

```

I gotta say, the build process is really difficult, Does everyone face this much difficulty? And thank you for actually reading through this much error trace, I know it tests patience. Thanks :)

**Comment by netlovers** [comment]
I don't know how many have difficulty building this. I built it yesterday, and it worked.
The real error message is this:
```
../src/sockios.cc:48:62: error: 'SIOCSIFNAME' was not declared in this scope
```
Looks like something is still missing, but I'm not sure what.
`SIOCSIFNAME` should be declared in `sockios.h` but I'm not sure if the build process uses your main OS's version of the file, or the previously built one. Maybe @piranna can answer that.

**Comment by ayusun** [comment]
Wow, So i tried everything again and it worked.

I got a message saying 

Success!
You Just Built a Custom NodeOS Image 
------------------------------------------

- Interactively run your image with:


and then when i try

npm start

it says
Could not access KVM kernel module: No such file or directory
failed to initialize KVM: No such file or directory

**Comment by netlovers** [comment]
Remove this line, and it will work:
https://github.com/NodeOS/NodeOS/blob/b8e317265f9208fe4df0a164c4f4f7ecf3bc77e4/scripts/start#L34

**Comment by ayusun** [comment]
Oh wow, it worked.

That was a bit difficult. But i guess from now on it would be easier. Thanks for all the help. I really appreciate it.

Let me see, in which areas I can help in. For now it seems, it would be regarding some shell commands.

If there are any doubts or something do we open an issue here or do we have some mailing list for that. 

Thanks :)

**Comment by netlovers** [comment]
I only check the issues, so feel free to open a new one here.

**Comment by ayusun** [comment]
Ok. Thank you :+1:
